### ISSUE TITLE
AzureChatGPT Mobile View

### ISSUE THREAD

**Issue by oliverlabs** [giuliohome/giuliohome.github.io#1]
Hi @giuliohome, you promised to share some code on how you made the azurechatgpt app mobile friendly. Can you please make a PR to my fork for this?

**Comment by giuliohome** [comment]
Ok. I'll try in this weekend to clean my code that is rough and just for me. Do not expect too much. See you soon

**Comment by oliverlabs** [comment]
Cheers!

**Comment by giuliohome** [comment]
[Done](https://github.com/oliverlabs/azurechatgpt/pull/3)!

Let me know if it is working or you, I've tested it in my codespaces.

The new button is this
![image](https://github.com/giuliohome/giuliohome.github.io/assets/3272563/5c903633-d82e-4bf3-8400-369098b24d74)

When closed
![image](https://github.com/giuliohome/giuliohome.github.io/assets/3272563/73b2fc0d-5284-4c91-84e8-96bb28dee283)

Opened instead
![image](https://github.com/giuliohome/giuliohome.github.io/assets/3272563/8617f7ee-fe33-4ea9-9fd9-8f4d2a6449ba)

**Comment by oliverlabs** [comment]
It looks cool. Unfortunately, I couldn't replicate it in another repo. I really need to learn TypeScript :) 

I go the following npm compilation error:

- info Creating an optimized production build...
- info Compiled successfully
- info Linting and checking validity of types...
Failed to compile.

```
./app/reporting/layout.tsx:16:8
Type error: Type '{}' is missing the following properties from type 'Prop': isOpen, setIsOpen

  14 |   return (
  15 |     <>
> 16 |       <MainMenu />
     |        ^
  17 |       <div className="flex-1">{children}</div>
  18 |     </>
  19 |   );
Error: Process completed with exit code 1.
```

**Comment by giuliohome** [comment]
Which is the "**other repo**" you mention? and yes you are missing those props in the Main : it should be like 

```ts
            <MainMenu isOpen={isOpen} setIsOpen={setIsOpen} />
```

See https://github.com/giuliohome-org/azurechatgpt-oliverlabs/blob/main/src/app/chat/context.tsx

**Comment by giuliohome** [comment]
Those mentioned props only because I wanted to hide also another component, the external left menu, otherwise you can simply include the useState hook in one single component.

Btw, this.topic is more related to react than to typescript. Of course all learn it because it's widespread but there are other alternative, for example in the dotnet field you can find awesome Avalonia and F#.... Back to the original issue, @oliverlabs let me know if we can close this ... or do you have other questions?

Cheers

**Comment by oliverlabs** [comment]
> Which is the "**other repo**" you mention? and yes you are missing those props in the Main : it should be like
> 
> ```ts
>             <MainMenu isOpen={isOpen} setIsOpen={setIsOpen} />
> ```
> 
> See https://github.com/giuliohome-org/azurechatgpt-oliverlabs/blob/main/src/app/chat/context.tsx

I changed it, but it still errors out during the compilation. Thanks for proposing the alternatives. I'll have a look! 

Did the app compile fully for you? As for the repo, it's a private fork of the same app.

**Comment by giuliohome** [comment]
Sorry, now I see what you mean in your Github Action here 
https://github.com/oliverlabs/azurechatgpt/actions/runs/6071119823/job/16468501217

Ok, I'll have a look at it now.

**Comment by giuliohome** [comment]
> Did the app compile fully for you? 

It was a "_linting_" error (_after_ the optimized prod build, as I mentioned other approaches - F# WebSharper or Fable or C# Avalonia - would have been more strongly typed), anyway @oliverlabs please merge my [PR fix](https://github.com/oliverlabs/azurechatgpt/pull/4) now and let's check the Github Actions again.

**Comment by giuliohome** [comment]
The [build is ok](https://github.com/oliverlabs/azurechatgpt/actions/runs/6083484381/job/16503437195) now.

**Comment by oliverlabs** [comment]
Thanks! Yeah, it worked.

**Comment by giuliohome** [comment]
I'm glad to hear that! Notice I've also added a last, little _visualization_ [fix](https://github.com/oliverlabs/azurechatgpt/pull/5).

**Comment by oliverlabs** [comment]
Have you seen the new repo version? @giuliohome 

microsoft/azurechat. It is missing the mobile view again, though :D

**Comment by giuliohome** [comment]
Yes, seen, let's move this discussion [there](https://github.com/microsoft/azurechat/issues/183) 👍
